### ISSUE TITLE
Seasoning Rack won't produce any salt sometimes

### ISSUE THREAD

**Issue by MidCoard** [GlobbyPotato/Rockhounding_Chemistry#114]
I play the mod in my private server.
It worked when I restart my server,And after a while, it produced nothing only consuming my rawsaltblock.

**Comment by GlobbyPotato** [comment]
Hi, I couldn't find the issue, Did you try breaking the block to see if it fixes or it does it again?

**Comment by MidCoard** [comment]
Version: Rockhounding Mod: Chemistry 1.12.2-3.46
(OK,just 19 hours ago,it updated.But what i am saying next is in this version 3.46) 

Yes,I have tried so many times.But the result is the same.
I have recorded a video to show my issue(mp4 is not allowed so I use the gif).

And also,I think I find one mistake in the guide book.
Look at my pics,the first one is the guide of the Deposition Chamber,but i did not find the core-block called Vapor Deposition Controller by using my JEI.
So I used the "give" command to get the block and i got it,but it is one-block-tall block and as I put two together just like the guide they disappeared.
However, I have used my JEI finding another block called Vapor Deposition Chamber (it is different from the guide).And this one is useful as the guide said.
So I think the one in the guide book is wrong.
And also,I have one question: what's the use of the Vapor Deposition Controller?

If the new version 3.47 has fixed these bugs, I'll tell you later(may be 12 hours).

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/24197013/74852896-26c75500-5378-11ea-81c1-a3de70257a37.gif)

![2](https://user-images.githubusercontent.com/24197013/74850860-6c365300-5375-11ea-898d-9532384f40c2.png)
![1](https://user-images.githubusercontent.com/24197013/74850912-7b1d0580-5375-11ea-91bb-7044ac19dbe2.png)

**Comment by MidCoard** [comment]
Also as you can see,the receipt in JEI is also changed(the result of the receipt is nothing).And as I was filming it,I also found that sometimes one rawsaltblock can turn to 64 salt items(it is a pity that I did not film it).

**Comment by MidCoard** [comment]
Also I would say I did not changed any receipt about rockhounding.And at first it worked successfully.But time changed everything(good).

**Comment by GlobbyPotato** [comment]
Thanks for the images, JEI breaking as well gave me the clue. I think I found the odd behaviour from the rack. It was not explicit at first, recipe altered itself over time, returning different amounts (got 64 as well when output filled). It seems to work now. It should return 9 salt items out of one block, so it should stop only if there's not enough room in the output slot.

About the Deposition Chamber you are right, the block indicated in the book is the upper part (it is not visible because placed by itself). You need to place the one with metadata 4 which will place a 2 blocks tall machine. Chamber and Controller are parts of the same machine placed at once. Will fix it too, thanks for spotting it.
