### ISSUE TITLE
Fixed bed reactor crach

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#121]
https://gist.github.com/wormzjl/293a06359e09eb72d6b5565d6a338ccb

Happens when trying to shift-click a catalyst into the reactor

**Comment by GlobbyPotato** [comment]
HI, I couldn't reproduce the crash on shiftng the catalysts but found an issue that actually prevented to insert any catalyst inside. Probably it's the same case. will put up a fix as I can, in case it solves. Tnx

**Comment by wormzjl** [comment]
Seems to happen after selecting the recipe, and when I open the reactor body GUI and hover on the catalyst itself
Doesn't happen if no recipe is selected

**Comment by wormzjl** [comment]
Allright, after updating it no longer crashes, however the machine is not doing any work.
I've built it just like in the manual and it's correctly fed with RF+heat and any ingredients/catalysts
![image](https://user-images.githubusercontent.com/2989009/82748733-951b1980-9da4-11ea-913c-4d088191c5f2.png)

**Comment by GlobbyPotato** [comment]
I cannot test it for a couple of days, meantime, did you tried with holders instead of vessels? The catalysts work as multipliers, so if the recipe says it consumes 0.200cu, 8x catalysts will consume 0.200*8 cu. You can use as many catalysts you want, no need to be 8. That's for balancing in case of custom recipes with costly catalysts.
In case the filter says "Thin air" it is just a placeholder for the server block to route the ingredients, they must remain empty or removed. 
I still need to fit this in the documentation.

**Comment by wormzjl** [comment]
Seems that changing to gas holder works...The recipes produces liquid by a multiplier of number of catalysts, I think this needs to be mentioned a bit more in the handbook

**Comment by wormzjl** [comment]
Also...Fixed bed reactor IRL :)
![image](https://user-images.githubusercontent.com/2989009/82753209-34033e00-9dc4-11ea-9b8e-777482291020.png)
