### ISSUE TITLE
[Suggestion] Fluidpedia Quickfind

### ISSUE THREAD

**Issue by Primitive-Human** [GlobbyPotato/Rockhounding_Chemistry#149]
**Problem:** Right now it takes many clicks to find the right letter under which a fluid is listed in the Fluidpedia, like from letter A to M to T. 

**Proposed solution:** Either a search box like in the fluid selection wrench in Pressure Pipes or the Logistics frames in Pneumaticcraft Repressurized,  or pressing a button combo while in the Fluidpedia screen to quickly go to the liquids and gases listed under the letter that was pressed:  Shift or Ctrl + C would quickly bring you to the liquids and gases listed under C.

**Comment by gatoborrachon** [comment]
Along with this, i think that it could be helpful to add the Registry Name of each liquid to its Info box (inside the Fluidpedia).

Context:
When a mod has a translated name for a liquid (for example, Original name:LiquidSulfurDioxide, Translated name:Dioxido de Azufre Liquido) it makes a bit harder to find that liquid (especially when you have hundreds of liquids)

**Comment by GlobbyPotato** [comment]
Hi, good point indeed. Though I avoided using the key typing because they seem to still abide the binding for what I see.
I made a fix in the Fluidpedia to make things much easier. Added a side bar with all the chars so you just click and show the content. Also in the tooltip you should be able to see the registry name. Material is still sorted by registry because in other language it may indeed fall into a different place.

Example:
Material: Sulfuric Acid
Registry: fluid.sulfuric_acid

**Comment by gatoborrachon** [comment]
ok, no worries, i just need the Registry Name, at least for me the issue is fixed, lets see what @DoctorWeirdGuy thinks about this to close the issue.

**Comment by Primitive-Human** [comment]
I'm content with the addition of the side bar that makes using the fluidpedia easier (and faster). Closing issue.
