### ISSUE TITLE
request: more flexibility with salt making

### ISSUE THREAD

**Issue by Divineaspect** [GlobbyPotato/Rockhounding_Chemistry#16]
We'd appreciate if we could have a more, flexible, salt fabrication method

- Heating the Evaporation Tank
- Cold Biomes having increased evaporation based on altitude
- Being able to set dimensions (such as the moon) where the lack of air results in highly rapid evaporation.
- A configurable time to cover the evaporation tank from rain to prevent progress from being lost

**Comment by GlobbyPotato** [comment]
Hi, thanks for the feedback. Working on fitting them: I hope it suits:

**- Heating the Evaporation Tank**
This is not possible I'm afraid. The feature depicts natural evaporation, that's why you have the different stages. Boiling water by default would be a straight conversion water-salt killing the feature at once.

**- Cold Biomes having increased evaporation based on altitude**
I'm adding an advantage over each specific biome evaporation time from level 150+. Got to make it high enough to be balanced and make sense though.

**- Being able to set dimensions (such as the moon) where the lack of air results in highly rapid evaporation.**
I added meantime a blacklist to disable evaporations in certain dimensions and a "space list" to represent the "no air" dimensions. Here the evaporation stages will be replaced by the instantly evaporation revealing salt. OP enough for autimation.

**- A configurable time to cover the evaporation tank from rain to prevent progress from being lost**
That's a nice idea. Added a configuration value that will preserve the progress for N ticks before melting to water. The evaporation is still paused by default during rain, so it's fine to do weather control stuff or sleeping. For more realism, the tank will also take a few seconds before filling when it starts raining.

**Comment by Divineaspect** [comment]
150+ is unreasonable for vanilla worldgen

**Comment by GlobbyPotato** [comment]
It must set a difference to make sense adding it. If it's too close the average playing levels it will be just an unnecessarily ticking code. Haven't tested BoP and RTG yet, IIRC BoP has a bunch of biomes reaching by default 100-200 so possibly no lower than 110-120 should be the final choise.

**Comment by Divineaspect** [comment]
120 is the highest mountain I've ever seen in vanilla or quark worldgen, so yeah, that makes sense.
