### ISSUE TITLE
[1.12.2 - 3.00] Left-clicking on rotated (with TF hammer) machines causes crash

### ISSUE THREAD

**Issue by NitroToxin2** [GlobbyPotato/Rockhounding_Chemistry#21]
Not sure if the experimental version is open for issues reports but if it is, here's one:

I've tried to rotate a Fluid Tank (filled with some water) with Crescent Hammer from Thermal Foundation, and seems like this caused the tank to reset its internal storage (the water disappeared). Also the game crashes (https://pastebin.com/QZPiCEU3) if I try to left-click on the tank after that (right-click works fine and opens the GUI). This happens with any other machine.

**Comment by GlobbyPotato** [comment]
Hi, you should not use any modded wrench on any machines from this mod because their facing (hence rotation) is handled differently. I'll eventually handle the rotation internally with the mod wrench.

If after the wrench crash the block is permanently corrupted, give yourself a Tile Nullifier from JEI and shift-rightclick it to reset and drop the block.

**Comment by NitroToxin2** [comment]
Aha, thank you for the answer. I was in the test world so I removed the block with explosion but it is good to know about the Tile Nullifier.

Could you prevent other wrenches to be used on the Rockhounding machines in the future updates?

**Comment by GlobbyPotato** [comment]
I can give a try if I get to intercept their action.
