### ISSUE TITLE
[Stupid Question] How to insert crushing gear into the mineral sizer.

### ISSUE THREAD

**Issue by HarryTsui313** [GlobbyPotato/Rockhounding_Chemistry#33]
Emm... I don't know how to get the mineral sizer working even after reading the guidebook. This is such an interesting mod featuring detailed industrial processes in Minecraft. I really want to give this mod a try but I was stuck in the basics ..... Thank you.

**Comment by GlobbyPotato** [comment]
The crushing gears go inside the Crushing Tanks, the two blocks behind the controller, you need 4 gears each block.

**Comment by HarryTsui313** [comment]
I tried the setup above but it failed. What components I need and what is the setup in order for the mineral
sizer to start grinding mineral ores and coal blocks?

**Comment by osirisgothra** [comment]
Yes I know its closed but for people who stumble here and/or an fyi to the devs:

Just a note on this, it seems it can be a bit misleading (the arrows*) in the screenshot, maybe a summarized rundown like "step 1: place XXX while facing YYY explanation would help to disambiguate. In Multiblock Madness (1.12.2) the players tend to get "thrown" into rockhounding, and since its optional, many give up when they have trouble with getting the first machine to work...

_*The arrows are ambiguous because some thing 'i need to face in the arrows direction' while others thing 'i need to have the _block_ facing in the arrow's direction'. This is because other mods are known to use both (one or the other)._  (this info's validity could change depending on the pack/version of rh/mc)
