### ISSUE TITLE
Transposer not working

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#35]
I'm using rockhounding_chemistry-1.12.2-3.13
After switched on the device does not seem to be converting normal fluid/gases to rockhounding compatible ones, even if the fluid is added by rockhounding itself.
Tested: steam (both the fluid named "steam" and "water_vapour"), all RH fluids

**Comment by wormzjl** [comment]
Maybe I misunderstood this, do I have to use a MT script to add each conversion manually?
Like mods.rockhounding_chemistry.Transposer.add(<liquid:water_vapour>*1000, <liquid:water_vapour>*1000);

**Comment by GlobbyPotato** [comment]
Hi, yes, you need CraftTweaker because the script is universal, so you can convert any fluid/gas into any other you want so need to tell what are fluidA and fluidB.
In example
`mods.rockhounding_chemistry.Transposer.add(liquid:water_vapour*1000, liquid:steam*1000);`
will convert my steam into mekanism steam
`mods.rockhounding_chemistry.Transposer.add(liquid:ic2superheated_steam*1000, liquid:ic2superheated_steam*1000);`
will let you use the ic2 steam inside RH.
The amount is not relievant, the block has its own rate

**Comment by wormzjl** [comment]
Thanks for clarifying this!
