### ISSUE TITLE
Bugs and suggestions, part 2

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#36]
Hello, I've tested the mod a bit more and the details with each device is really astonishing.
Here are some bugs I found so far:
1. If the profiling bench is attached to a (activated) server with configured server file, the patten in the profiling bench cannot be changed even after the server is switched off. I'd recommend checking the logic of other devices using the server too.

2. Server attached to the lab oven cannot select recipes.

3. The power input sign on the gas condenser / expansion chamber seems to be incorrect(old texture?) .

4. The working speed for the expansion chamber is much slower that the condenser, IMO the speed should be inverse?

5. Lab blender keep its progress bar even if input item is removed.

And a couple of suggestions for a better player experience:
1. When using the retention vat, slurry agitator for the first sealed vat can only be introduced from below, which could be problematic for certain setups. I'd suggest allowing the fluid input from below, so that hopper with new slurry agitators can be put on its side.

2. For the retention vat, is it possible to allow crafttweaker removal of shards on the default list? I just want a couple of them to be unobtainable by this method, but its pretty complicated to remove the whole list and write from scratch.

3. A global or machine specific power usage mulitiplier would be nice for precise control of game balance. And a config option for the use time (durability) of different types of consumables (glasswares, catalysts, grinding gears, slurry agitators) would be great.

4. I see that one can manually empty the fluid containers, however in large scale automations this might be complicated. For example I want to use a lot of argon in my process but not that much of oxygen/nitrogen, and when automated I have to check manually if these gas holders are full, otherwise the system will get stuck. To get over this problem I'd suggest adding a switch in the gas holder, which allows it to "dump" all excess gas when full, thus prventing such a bottleneck.

5. Allow clicking the sampling ampoule in the fluid container gui to have a sample of fluids/gases, this is especially helpful when setting up filtered fluid storage for the GAN tower.

6. Is it possible to add crafttweaker support for the GAN tower?

7. Could you add a solid input slot for the gasifier? If this don't make too much work... 

8. Do you have any plan for machine sounds?

9. The fluid tank can hold 100 buckets of liquid in a single block, which seems a bit op to me with it's price...

Thank you!

**Comment by wormzjl** [comment]
Also I'm getting some graphical glitches with the rendering...
![image](https://user-images.githubusercontent.com/2989009/40621043-8acdd13e-629b-11e8-802a-98a91216fce8.png)

**Comment by GlobbyPotato** [comment]
Hi, thanks, good poinintgs.

As for the bugs:
-the lab oven and the profiling bench should work now, just derped some variables on them.
-fixed the power plugs and the glitching textures. About the glitching textures the problem is that they don't glitch here so I can discover them from streamers and from reports. Let me know if any other is behaving the same.
-condenser and expander don't have a working speed, they process per tick the quantities indicated in the recipes as soon as the device is turned on (they share the same recipes, just reversed). in example it condenses nitrogen 70:1 into its liquid form and expands 1:70 into its gas form (the recipes have convenience values).

As for the suggestions:
-every fluid tank takes fluid from any side, you could pump it from below and use the hopper on the side. Once correctly assembled the structure, the exposed colored plugs are only indicative to tell what the block actually does with the "outside", they are mandatory only for the gas devices.
-to remove the shards I could try to add an inhibit command like for the extractor, will take some time though because it involves the process.
-the consumable uses are already in the config. I removed at some point the catalyst uses because they have tier purposes so I'm not sure if setting them back. I could either add a global multiplier so you have all the uses x1 x2 x3, or make the catalyst sensible to the Unbreaking enchantment. There is still the option of internally regen the catalysts for the long running machines. I'm not sure what you mean with the power multiplier, do you mean multiply the rf/tick required by the machine? I suppose it's doable. The current ones would be 1x. The fuel power instead depends on the machine speed and follows the furnace method for coherence.
-the "Dump when full" is definitely a good idea, will try to add it. In the GAN Plant though, I guess it will be easier if I drop the channel requirement for the rare gases so each channel can work on its own. This would complete the previous update to disable single rare gases. If I want to be cruel I could also consider to add a configurable chance of incidents when dumping stuff. I remember people liked this chance on other mods (those were famous mods though).
-the ampoule addon sounds fair. Will try to add it too.
-unfortunately no crafttwaker for GAN I'm afraid. The machine work is specific so it turned out pretty hardcoded.
-the solid input to the gasifier could be done replacing the cistern with an internal funnel or grinder when needed. Though would require a rewrite of the function of the structure. Still doable but at the end of the queue.
-I thought about sounds and particles. I dropped them to avoid to charge the mod, in case it was already too laggy.
-the iron drum hold 256B and is still easy to make. The recipe for the fluid tank balances the iron required for the other parts of the mod I guess. I added 4 rods in the recipe to make it a little more expensive but don't really see a problem since the mod is anyway supposed to handle large amount of material. At least it gives people a reason to prefer it for once. You can alter it with crafttweaker.

**Comment by wormzjl** [comment]
Thanks for the quick fix. Some environmental effect will surely be interesting!
For the power usage, it could be like a big wrapper around the final values.
