### ISSUE TITLE
Broken OreDict. + wrong recepie for nichrome.

### ISSUE THREAD

**Issue by VoltEnno** [GlobbyPotato/Rockhounding_Chemistry#45]
So... Chrome ore dict is broken, since it's called "chromium" and most mods use "chrome" and also in nichrome there are 23 % of chrome, not 1, ya know.

**Comment by GlobbyPotato** [comment]
You are right, it's iron to be 1, the ingredients were swapped. Thanks will fix it.

I used "chromium" because it's the chemical element you extract while "chrome" is a processed chromium. Back in time I found a couple of mods or packs obtaining "chrome" from machines treating than ores, so I decided to go carefully at naming stuff. Will see again about it later, they could even cohexist as separated or depending materials fwiw.
