### ISSUE TITLE
Gears cause resource duplication with other mods.

### ISSUE THREAD

**Issue by TheRedMelon** [GlobbyPotato/Rockhounding_Chemistry#50]
Gears in almost all other mods require four ingots of their material to create.  By having the gears in this mod registered in the ore dictionary, you can create a gear of the desired material with rockhounding then, for example, put it in the tinkers' construct smeltery and have it turned into four ingots.  It's not just tinkers' construct.  In my mod pack, it also works with the induction smelter from thermal expansion.  This will probably work with any mod that allows turning gears into ingots and have their recipes use oredict.

Not sure how you would go about solving it but maybe a config option to remove registering them into the oredict?

**Comment by GlobbyPotato** [comment]
Hi, removing the oredict is not the case, the point is being inclusive not otherwise. The best I can do is replace the ingot with the block so you have 2 gears for 9 ingots, which smelt back into 8 ingots. That would make sense because you are not casting here but kind of profiling, so expect to leave behind bits of material.
This made me think that the iron gear should be dropped from oredict indeed, because it's a large scale consumable inside the mod and not comparable to other gears.
