### ISSUE TITLE
(suggestion) function for chemical waste

### ISSUE THREAD

**Issue by falizure** [GlobbyPotato/Rockhounding_Chemistry#54]
while playing around with some of the chemicals it occured to me it would be really neat to have some sort of in world benefit for chemical waste, the first and most obvious would be to act as a poison to anyone who touches it in which case it could be called toxic waste or something similar, but i also think it would be much more...intriguing if it had more to it then even that, perhaps acting as a mob spawning mechanic, ether on its own or dropping animals or villagers in and converting them into hostile mobs, while minor it could give more incentive to not just void it, perhaps make poison potatoes as well, and depending on how truly crazy you wanted to get with it maybe even mutated creatures.

**Comment by GlobbyPotato** [comment]
I was already thinking about how to extend the chemical waste usage with a whole themed feature. There are still some limitations because I haven't yet worked with custom mobs editing, so it's still a plan.
Frankly I'm not bothering with the poisoning part, any acid in the mod will just kill you. Plain simple.
The chemical waste itself at the moment can drop XP if an entity dies in it and is consumed inside the Orbiter to multiply the value of the picked XP orbs.
The item mutation was in list too. I didn't actually thought about poisonous potatoes, keep forgetting they even exist but yeah it's sort of that.
