### ISSUE TITLE
RH hot fluids touching water causes heavy lag

### ISSUE THREAD

**Issue by wormzjl** [GlobbyPotato/Rockhounding_Chemistry#74]
See https://youtu.be/jABeO8wBFcc
However is it even a RH issue?

**Comment by GlobbyPotato** [comment]
I noticed it happens only with molten metals and slurries, seems like it's caused by the heavy difference in density and viscosity because. It's like the molten slowly updates to expand then the water updates itself to expand back and they never settle. Water-like acids settle immediately instead.
I don't like fluids because they lag the hell out of my game because of the constant updates.

**Comment by GlobbyPotato** [comment]
ok after some laggy fluid tests I found out the origin of the glitch. It is fixed and cleaned now!

**Comment by wormzjl** [comment]
There is still some minor lagspikes when 2 fluids are in contact, but much better now

**Comment by GlobbyPotato** [comment]
Fluids should behave now like any other fluids. it may depend on the fact that each one updates itself when touching while flowing down. Placing them next to eachother on a flat world I didn't find spikes, they just settled.
