### ISSUE TITLE
ContentTweaker Items wont work in Lab blender

### ISSUE THREAD

**Issue by Freebi85** [GlobbyPotato/Rockhounding_Chemistry#80]
Hello =)

I created via crafttweaker a few recipes for the Lab Blender. With components of Content Tweaker it doesn't seem to work. It's not a serious mistake but I wanted to ask if something can be done.

Freebi

**Comment by GlobbyPotato** [comment]
I'd need to see the blender scripts you made to have an idea. Haven't used ContentTweaker so I can't tell what are its components.

**Comment by Freebi85** [comment]
Here an example

val comp = <contenttweaker:chem_comp>;
val ele_ender = <contenttweaker:ele_enderium>;
val sodiumcell = <techreborn:dynamiccell>.withTag({Fluid: {FluidName: "sodium_hydroxide", Amount: 1000}});

mods.rockhounding_chemistry.LabBlender.add([ele_ender, ele_ender, ele_ender, ele_ender, ele_ender, sodiumcell, comp], <thermalfoundation:material:167>);

**Comment by GlobbyPotato** [comment]
I gave it a quick test with default stuff and it actually worked. As long as the ContentTweaker items/blocks are correctly registered at the correct event they should be part of the recipe.
One thing you may consider is the structure of the recipe, since you need 4 ele_ender you may want to write the script this way:

val ele_ender = <contenttweaker:ele_enderium>*4;
val comp = <contenttweaker:chem_comp>;
val enderium_ingot = <thermalfoundation:material:167>
val sodiumcell = <techreborn:dynamiccell>.withTag({Fluid: {FluidName: "sodium_hydroxide", Amount: 1000}});

mods.rockhounding_chemistry.LabBlender.add([ele_ender , sodiumcell, comp], enderium_ingot);

**Comment by GlobbyPotato** [comment]
of course remember the brackets of doom removed by the post editor

**Comment by Freebi85** [comment]
This is how it works! Thank you very much I will customize my scripts.
Freebi
