### ISSUE TITLE
crafttweaker error

### ISSUE THREAD

**Issue by RufousFox** [GlobbyPotato/Rockhounding_Chemistry#92]
hi, i have some prblems with crafttweaker...   I added new fluids with contenttweaker and tried to add crafts with them...   and I have two active and several non-working crafts with unknow errors...  what wrong with that?
crafttweaker code:
`
mods.rockhounding_chemistry.SlurryPond.add(<immersiveengineering:metal>, <liquid:nitric_acid>*500, <liquid:liquidnitricdioxid>*500); //working
mods.rockhounding_chemistry.SlurryPond.add(<forestry:ingot_copper>, <liquid:nitric_acid>*500, <liquid:liquidnitricdioxid>*500); //working
mods.rockhounding_chemistry.SlurryPond.add(<fp:itemerze:2>, <liquid:nitric_acid>*500, <liquid:liquidnitricdioxid>*500);//working
mods.rockhounding_chemistry.SlurryPond.add(<galacticraftcore:basic_item:3>, <liquid:nitric_acid>*500, <liquid:liquidnitricdioxid>*500);//working
mods.rockhounding_chemistry.SlurryPond.add(<magneticraft:ingots:2>, <liquid:nitric_acid>*500, <liquid:liquidnitricdioxid>*500);//working
mods.rockhounding_chemistry.SlurryPond.add(<nuclearcraft:ingot>, <liquid:nitric_acid>*500, <liquid:liquidnitricdioxid>*500);//working
mods.rockhounding_chemistry.SlurryPond.add(<rockhounding_chemistry:metal_items:11>, <liquid:nitric_acid>*500, <liquid:liquidnitricdioxid>*500);//working
mods.rockhounding_chemistry.LabOven.add("monometilamin sintez", <rockhounding_chemistry:zn_catalyst>, null, <liquid:ammonia>*500, <liquid:methanol>*500, <liquid:monometilamin>*800, null, null); //working
mods.rockhounding_chemistry.LabOven.add("dimetilamin sintez", <rockhounding_chemistry:zn_catalyst>, null, <liquid:ammonia>*500, <liquid:monometilamin>*500, <liquid:dimetilamin>*1000, null, null); //working

mods.rockhounding_chemistry.GasCondenser.add(<liquid:dimetilamin>*1, <liquid:liquiddimetilamin>*100); //not working
mods.rockhounding_chemistry.GasCondenser.add(<liquid:nitricdioxid>*1, <liquid:liquidnitricdioxid>*100);//not working
mods.rockhounding_chemistry.GasCondenser.add(<liquid:dinitrotetraoxide>*1, <liquid:liquiddinitrotetraoxide>*100);//not working
mods.rockhounding_chemistry.GasCondenser.add(<liquid:dimetilgidrosin>*1, <liquid:liquiddimetilgidrosin>*100);//not working
mods.rockhounding_chemistry.GasCondenser.add(<liquid:liquiddimetilamin>*100, <liquid:dimetilamin>*1);//not working
mods.rockhounding_chemistry.GasCondenser.add(<liquid:liquidnitricdioxid>*100, <liquid:nitricdioxid>*1);//not working
mods.rockhounding_chemistry.GasCondenser.add(<liquid:liquiddinitrotetraoxide>*100, <liquid:dinitrotetraoxide>*1);//not working
mods.rockhounding_chemistry.GasCondenser.add(<liquid:liquiddimetilgidrosin>*100, <liquid:dimetilgidrosin>*1);//not working

mods.rockhounding_chemistry.GasReformer.add(<liquid:dimetilamin>*1000, <liquid:nitric_acid>*1000, <liquid:nitrosodimetilamin>*2000, null);//not working
mods.rockhounding_chemistry.GasReformer.add(<liquid:nitrosodimetilamin>*1000, <liquid:hydrogen>*1000, <liquid:dimetilgidrosin>*2000, null);//not working
mods.rockhounding_chemistry.HeatExchanger.add(<liquid:nitricdioxid>*100, <liquid:dinitrotetraoxide>*100);//not working`

and errors:
`[INITIALIZATION][CLIENT][ERROR] Invalid recipe detected for Gas Condenser
[INITIALIZATION][CLIENT][ERROR] Invalid recipe detected for Gas Condenser
[INITIALIZATION][CLIENT][ERROR] Invalid recipe detected for Gas Condenser
[INITIALIZATION][CLIENT][ERROR] Invalid recipe detected for Gas Condenser
[INITIALIZATION][CLIENT][ERROR] Invalid recipe detected for Gas Condenser
[INITIALIZATION][CLIENT][ERROR] Invalid recipe detected for Gas Condenser
[INITIALIZATION][CLIENT][ERROR] Invalid recipe detected for Gas Condenser
[INITIALIZATION][CLIENT][ERROR] Invalid recipe detected for Gas Condenser
[INITIALIZATION][CLIENT][ERROR] Invalid recipe detected for Reforming Reactor
[INITIALIZATION][CLIENT][ERROR] Invalid recipe detected for Reforming Reactor
[INITIALIZATION][CLIENT][ERROR] Invalid recipe detected for Heat Exchanger`

**Comment by GlobbyPotato** [comment]
Hi, let's see if we can sort them:

These lab oven scripts are somewhat wrong because you are consuming a catalyst each process while it has a durability and should last longer:

`mods.rockhounding_chemistry.LabOven.add("monometilamin sintez", <rockhounding_chemistry:zn_catalyst>, null, <liquid:ammonia>*500, <liquid:methanol>*500, <liquid:monometilamin>*800, null, null); 
mods.rockhounding_chemistry.LabOven.add("dimetilamin sintez", <rockhounding_chemistry:zn_catalyst>, null, <liquid:ammonia>*500, <liquid:monometilamin>*500, <liquid:dimetilamin>*1000, null, null); `

Catalysts must be the second solid ingredient and using only catalyst is not possible. In order to use a catalyst, the scripts need to be at least like these:

`mods.rockhounding_chemistry.LabOven.add("monometilamin sintez", <any_mod_id:any_item_name:any_meta>,<rockhounding_chemistry:zn_catalyst>, <liquid:ammonia>*500, <liquid:methanol>*500, <liquid:monometilamin>*800, null, null); 
mods.rockhounding_chemistry.LabOven.add("dimetilamin sintez", "anyOredict", <rockhounding_chemistry:zn_catalyst>, <liquid:ammonia>*500, <liquid:monometilamin>*500, <liquid:dimetilamin*1000>, null, null); `

================================================================

In the Gas condenser scripts I see the recipes are doubled, 100 to 1 and 1 to 100. You need to use only the 100 to 1 form because the Gas Expander version is made automatically by reversing these:

`mods.rockhounding_chemistry.GasCondenser.add(<liquid:dimetilamin>*1, <liquid:liquiddimetilamin>*100);
mods.rockhounding_chemistry.GasCondenser.add(<liquid:liquiddimetilamin>*100, <liquid:dimetilamin>*1);`

The format of the script seems correct but I don't know what these materials are. To work you can try this form where dimetilamin is a gas and liquiddimetilamin is a fluid. In ContentTweaker you need to specify that dimetilamin is gaseous:

`mods.rockhounding_chemistry.GasCondenser.add(<liquid:dimetilamin>*100, <liquid:liquiddimetilamin>*1);`

================================================================

In the Gas Reformer scripts, the catalyst cannot be null. Also the first script seems wrong because nitric acid is a fluid while the inputs are both gases:

`mods.rockhounding_chemistry.GasReformer.add(liquid:dimetilamin*1000, liquid:nitric_acid*1000, liquid:nitrosodimetilamin*2000, null);
mods.rockhounding_chemistry.GasReformer.add(liquid:nitrosodimetilamin*1000, liquid:hydrogen*1000, liquid:dimetilgidrosin*2000, null);`

You need to add an item with a durability, in example one of the catalysts, or create one with ContentTweaker. Notice also that I replaced the nitric acid with a gaseous version:

`mods.rockhounding_chemistry.GasReformer.add(liquid:dimetilamin*1000, liquid:fuming_nitric_acid*1000, liquid:nitrosodimetilamin*2000, <rockhounding_chemistry:co_catalyst>);
mods.rockhounding_chemistry.GasReformer.add(liquid:nitrosodimetilamin*1000, liquid:hydrogen*1000, liquid:dimetilgidrosin*2000, <rockhounding_chemistry:fe_catalyst>);`

Please remember also that if you use quantities that are higher than 1000mB you need to use gas holders instead of pressure vessels or the low capacity won't make the Reformer work.

================================================================

The script of the Heat Exchanger should be correct. Remember that the temperature of the output must be lower than the temperature of the input for the recipe to be valid and both material must be labeled as gas. According to the ratio in the Condenser scripts, both nitricdioxid and dinitrotetraoxide are fluids not gases so they may not apply to this machine. The form should be this:

mods.rockhounding_chemistry.HeatExchanger.add(liquid:some_gas*100, liquid:some_cooler_gas*100);`

**Comment by RufousFox** [comment]
> The script of the Heat Exchanger should be correct. Remember that the temperature of the output must be lower than the temperature of the input for the recipe to be valid and both material must be labeled as gas. According to the ratio in the Condenser scripts, both nitricdioxid and dinitrotetraoxide are fluids not gases so they may not apply to this machine. The form should be this:
==================================================================
but nitricdioxid and dinitrotetraoxide it's gases not fluids...
diNitroTetraoxide.gaseous = true;
nitricDiOxid.gaseous = true;

and dinitrotetraoxide its cooled nitricdioxid in real...
(about condencer below)
==================================================================
what about gas condencer... I did not read the this "The same (reversed) recipe works for the Expansion Chamber." properly, sorry. 
==================================================================
"and using only catalyst is not possible".  I have reaction using zinc catalyst..  Do i need to add zinc ingot as catalyst and...  zinc catalyst as second item?... okay i will add only ingot but it's strange.... Use zinc ingot when i have zinc catalyst...
==================================================================
reforming reactor - fixed
==================================================================

**Comment by GlobbyPotato** [comment]
In the ContentTweaker script is there a parameter to assign a temperature to the created fluid/gas? If the gaseous parameters are set "true", then it should already work or either the temperatures are not assigned and by default the will all take 300K.
I'll give anyway a look at the integration code of the heat exchanger then, to see if something has gone wrong. 

About the condenser I admit the note was a bit misleading, it should mean the "same script". Will fix it but yes, you need one script only, the other one is self made.

For the lab oven, I've set it so that the solute does the reaction while the optional catalyst enhances it (see sulfuric acid producing more with catalyst), just for minecraft tiers reasons or every machine would look the same. You can try a zinc compound or dust for a normal recipe and a zinc compound + catalyst for a better production.

**Comment by RufousFox** [comment]
okay, i'm fixed that all. Thank you.
 But can you increase capacity of power station from 32k to 33-40k?
if i put block of coke coal (32k (from IE)) and when it burns down remain 200 units of heat...   and new block doesnt start to burn and machine dont work without energy

**Comment by GlobbyPotato** [comment]
good to hear they are fixed.
yeah, I can double the capacity of the power station, You can also burn anything for fuel automation, from lava to wood and syngas.

**Comment by RufousFox** [comment]
and now i have some problems with that.... (expansion chamber)
![123](https://user-images.githubusercontent.com/31186212/55276902-9f5d9700-530a-11e9-9423-f730702e5380.PNG)

i'm cheked perfomance of my scripts, and expansion didnt work...
I'm made new modpack (only rockhouding, crafttweaker and contenttweaker (without any scripts) and cores) and i have that...
I expemented on oxygen
Condencer make liquid oxygen, but expansion dont inverse that...
All input output connect correctly, power station have energy, activation button pressed
but nothing happens...

some scrins
![123](https://user-images.githubusercontent.com/31186212/55276976-0f205180-530c-11e9-97d2-62d4657f3a9c.PNG)
![image](https://user-images.githubusercontent.com/31186212/55276984-252e1200-530c-11e9-95d9-ffaf0cde8fcc.png)
![image](https://user-images.githubusercontent.com/31186212/55276991-36771e80-530c-11e9-9ccc-c1a10692cf53.png)
![image](https://user-images.githubusercontent.com/31186212/55276992-4131b380-530c-11e9-9bb7-9d32dfefb8f3.png)

**Comment by GlobbyPotato** [comment]
Found it! The vessel was not recognized in that place, something accidentally broke.
Thanks for spotting it, will make an hotfix asap.

**Comment by RufousFox** [comment]
thank

**Comment by GlobbyPotato** [comment]
Both core and mod are updated on curseforge. You should be able to test the power capacity and the expander fix.

**Comment by RufousFox** [comment]
okay, thank you
And now, i have a little factory of rocket fuel for galacti craft (
go through 7 laps of hell and fly away from the planet XD)

**Comment by GlobbyPotato** [comment]
Ready to inherit the stars! XD
At least it looks somewhat factory-ish. No pipes, no glory
![](https://www07.abb.com/images/librariesprovider104/Industry-solutions/Chemical/chemical-us-cyber-security.jpg)
If everything is fine, I'll close the issue. Let me know if I can help further.

**Comment by RufousFox** [comment]
okay, thanks again
